### ISSUE TITLE
Methylation reference atlas for deconvolution

### ISSUE THREAD

**Issue by Jonbroad15** [methylgrammarlab/cfdna-ont#1]
Dear authors,

I am trying to reproduce your cell-of-origin deconvolution results in supplementary figure 4 of your latest pre-print. I see that you created a new reference atlas with the top 1000 hyper/hypo-methylated CpGs for each cell type instead of the default atlas included in https://github.com/nloyfer/meth_atlas

Do you mind linking me to this reference atlas? I could not find it in the repository or data files.

**Comment by benbfly** [comment]
thanks for the comment. we have added the probe file here:
deconvolution_code/cell_type_probes/CpGs.100bp-block.1000.csv

we will also work on adding the code to generate this. we used exactly the method as described in the moss et Al. 2018 paper.
